name: flutterhive
description: Flutter - Hive
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  path_provider: ^2.0.13
  equatable: ^2.0.5
  dartz: ^0.10.1

  ## Local Storage Packages ##
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.2.4
  sembast: ^3.4.0
  shared_preferences: ^2.0.18



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:

  uses-material-design: true
